version: '1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: pastzookeeper
    environment:
    - ZOOKEEPER_CLIENT_PORT=2182
    - ZOOKEEPER_TICK_TIME=2000
  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: pastbroker
    ports:
    - "2020:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=pastzookeeper:2182
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:2020,PLAINTEXT_INTERNAL://pastbroker:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  pastmongo:
    image: mongo
    container_name: pastmongo
    volumes:
      - ./Database/data:/data/db
    ports:
      - "2021:27017"
  pastwebsocket1:
    build: ./Servers/WSS
    ports:
      - "2022:2001"
    environment:
      - API_PORT=2024
      - KAFKA_BROKER_SERVER=pastbroker:29092
      - NGINX_PORT=2024
    depends_on:
      - broker
      - nginx
      - pastmongo
  pasthttpserver:
    build: ./Servers/HTTP
    ports:
      - "2023:2001"
    environment:
      - API_PORT=2024
      - KAFKA_BROKER_SERVER=pastbroker:29092
      - NGINX_PORT=2024
    depends_on:
      - broker
      - nginx
      - pastmongo
  nginx:
    build: ./NGINX
    container_name: pastnginx
    ports:
      - "2024:80"